#!/usr/bin/env bash

# Restart the touchpad

# based on this awesome answer:
# https://askubuntu.com/a/706134/338982

function listXinput {
	xinput --list
}

listXinput

printf "\n\033[31;1m%s\033[0m\n\n" "Restarting device 15..."
xinput disable 15
xinput enable 15

listXinput
