#!/usr/bin/env bash

# Restart the touchpad
# based on this awesome answer:
# https://askubuntu.com/a/706134/338982

DEVICE_NAME="AlpsPS/2 ALPS GlidePoint"
DEVICE_ID=$(xinput --list --id-only "$DEVICE_NAME")

xinput --list

printf "\nFound device id %d of %s" $DEVICE_ID "$DEVICE_NAME"
printf "\n\033[31;1m%s\033[0m\n\n" "Restarting device $DEVICE_ID..."

xinput disable $DEVICE_ID
xinput enable $DEVICE_ID

xinput --list
